name: PythonTest
on: [push]
jobs:
  PythonTry:
    runs-on: ubuntu-latest

    steps:
	- name: Install dependencies
	run: | 
	 python -m pip install --upgrade pip
	 pip install flake8
	- name: Lint
	 run: |
	 flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
	 flake8 . --count --exit-zero --max-complexity=10 --max-line-lenght=127 --statistics
